services:
  workspace:
    build: .
    container_name: ${PROJECT_NAME:-ai-template}-dev
    runtime: sysbox-runc
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - path: .env
        required: false
    environment:
      - HOME=/home/ubuntu
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    volumes:
      - ./opencode/config/:/home/ubuntu/.config/opencode
      - ~/.local/share/opencode:/home/ubuntu/.local/share/opencode
      - ~/.claude/:/home/ubuntu/.claude
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
      - ../:/home/ubuntu/workspace
    working_dir: /home/ubuntu/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    networks:
      - default-network
    deploy:
      resources:
        limits:
          memory: 25G


networks:
  default-network:
    driver: bridge
