#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/slug.sh
source "${SCRIPT_DIR}/lib/slug.sh"

wasi_resolve_worktree_root
wasi_assert_not_main_checkout
wasi_derive_slug >/dev/null

cd "${WASI_WORKTREE_ROOT}"

echo "[docker_inner] bringing down stack 'wasi-${WASI_STACK_SLUG}'..."

# -v wipes volumes, which includes the signal-cli linked-device credentials.
docker compose \
  -p "wasi-${WASI_STACK_SLUG}" \
  -f docker_inner/docker-compose.yml \
  down -v --remove-orphans

# Remove generated .env.testing if it was written by up.sh
# Heuristic: check for the "Generated by docker_inner/up.sh" header comment
ENV_FILE="${WASI_WORKTREE_ROOT}/.env.testing"
if [[ -f "${ENV_FILE}" ]] && grep -q '# Generated by docker_inner/up.sh' "${ENV_FILE}"; then
    rm -f "${ENV_FILE}"
    echo "[docker_inner] removed generated .env.testing"
fi

echo "[docker_inner] stack 'wasi-${WASI_STACK_SLUG}' is down."
