#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/slug.sh
source "${SCRIPT_DIR}/lib/slug.sh"

__project_prefix___resolve_worktree_root
__project_prefix___assert_not_main_checkout
__project_prefix___derive_slug >/dev/null

cd "${__PROJECT_PREFIX___WORKTREE_ROOT}"

echo "[docker_inner] bringing down stack 'wasi-${__PROJECT_PREFIX___STACK_SLUG}'..."

# -v wipes volumes (any service credentials or persisted state are lost).
docker compose \
  -p "wasi-${__PROJECT_PREFIX___STACK_SLUG}" \
  -f docker_inner/docker-compose.yml \
  down -v --remove-orphans

# Remove generated .env.testing if it was written by up.sh
# Heuristic: check for the "Generated by docker_inner/up.sh" header comment
ENV_FILE="${__PROJECT_PREFIX___WORKTREE_ROOT}/.env.testing"
if [[ -f "${ENV_FILE}" ]] && grep -q '# Generated by docker_inner/up.sh' "${ENV_FILE}"; then
    rm -f "${ENV_FILE}"
    echo "[docker_inner] removed generated .env.testing"
fi

echo "[docker_inner] stack 'wasi-${__PROJECT_PREFIX___STACK_SLUG}' is down."
