#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/slug.sh
source "${SCRIPT_DIR}/lib/slug.sh"

__project_prefix___resolve_worktree_root
__project_prefix___assert_not_main_checkout
__project_prefix___derive_slug >/dev/null

cd "${__PROJECT_PREFIX___WORKTREE_ROOT}"

echo "[dev-container-inner] bringing down stack '__project_prefix__-${__PROJECT_PREFIX___STACK_SLUG}'..."

# -v wipes volumes (any service credentials or persisted state are lost).
docker compose \
  -p "__project_prefix__-${__PROJECT_PREFIX___STACK_SLUG}" \
  -f dev-container-inner/docker-compose.yml \
  down -v --remove-orphans

# Remove generated .env.testing if it was written by up.sh
# Heuristic: check for the "Generated by dev-container-inner/up.sh" header comment
ENV_FILE="${__PROJECT_PREFIX___WORKTREE_ROOT}/.env.testing"
if [[ -f "${ENV_FILE}" ]] && grep -q '# Generated by dev-container-inner/up.sh' "${ENV_FILE}"; then
    rm -f "${ENV_FILE}"
    echo "[dev-container-inner] removed generated .env.testing"
fi

echo "[dev-container-inner] stack '__project_prefix__-${__PROJECT_PREFIX___STACK_SLUG}' is down."
